INSERT INTO public.opposite_stats (category, stat_label, opposite_label, stat_value, opposite_value, source, impact_score) VALUES

-- Health
('health',
 'Most people sit 10+ hours a day',
 'Move every hour, walk 8,000 steps',
 '80% of adults are sedentary for 10+ hours daily',
 'Walking 8,000 steps/day reduces all-cause mortality by 51%',
 'JAMA Internal Medicine, 2020',
 9),

('health',
 '73% of adults never strength-train',
 'Lift weights twice a week',
 'Only 27% of adults meet strength-training guidelines',
 '2x/week resistance training adds ~3 years of healthy lifespan',
 'BMJ Open Sport & Exercise Medicine, 2022',
 8),

('health',
 'Average American sleeps 6.8 hours',
 'Protect 8 hours of sleep nightly',
 '35% of adults are chronically sleep-deprived',
 '8 hrs sleep = 40% better memory retention and 3x faster reaction time',
 'Matthew Walker — Why We Sleep, 2017',
 9),

('health',
 'Most people skip breakfast or eat sugar',
 'Eat 30g of protein within 30 min of waking',
 '31 million Americans skip breakfast daily; 60% eat high-sugar cereals',
 'High-protein breakfast reduces afternoon cravings by 60% and stabilizes energy',
 'American Journal of Clinical Nutrition, 2013',
 7),

-- Finance
('finance',
 '65% of Americans live paycheck to paycheck',
 'Automate saving 20% before you spend',
 '65% of U.S. adults have no financial cushion after monthly expenses',
 'Automating savings ("pay yourself first") 2x likelihood of building wealth',
 'LendingClub Financial Health Survey, 2023',
 10),

('finance',
 'Only 32% of adults maintain a budget',
 'Track every dollar with a zero-based budget',
 '68% of adults have no structured spending plan',
 'Budgeters are 2x more likely to hit savings goals and feel in control',
 'Gallup Financial Wellness Study, 2022',
 8),

('finance',
 'Average person wastes $2,400/year on unused subscriptions',
 'Audit subscriptions monthly, redirect to index funds',
 'Average household has 12 subscriptions; uses fewer than half regularly',
 '$200/month invested in index funds = $1M in 30 years at 10% average return',
 'Chase Consumer Spending Insights, 2023',
 9),

-- Productivity
('productivity',
 'Workers check email 96 times per day',
 'Check email only 3 times per day',
 'The average knowledge worker is interrupted every 6 minutes by email or messages',
 'Batching email to 3x/day increases deep work output by 40%',
 'UC Irvine Focus Study, 2016',
 8),

('productivity',
 '95% never review their goals after writing them',
 'Do a weekly 30-minute goal review',
 'Most people write New Year goals and never look at them again',
 'Weekly goal review increases goal achievement rate by 42%',
 'Dominican University Goal Study, Dr. Gail Matthews',
 9),

('productivity',
 'Most people multitask constantly',
 'Work in single-focus 90-minute blocks',
 '40% productivity loss occurs when switching between tasks',
 'Single-tasking in 90-min Ultradian rhythm cycles doubles output quality',
 'Peretz Lavie Ultradian Rhythm Research, 1982',
 8),

('productivity',
 'Only 8% achieve New Year resolutions',
 'Stack new habits onto existing ones',
 '92% of people who set New Year goals fail to achieve them',
 'Habit stacking (attach new habit to existing cue) = 60% higher success rate',
 'BJ Fogg — Tiny Habits, 2019',
 9),

-- Social / Mental
('social',
 'Average person spends 2.5 hrs/day on social media',
 'Cap social media at 30 minutes per day',
 'Global average social media use is 2 hours 27 minutes daily',
 '30 min/day limit correlates with 19% decrease in loneliness and depression scores',
 'University of Pennsylvania Experimental Study, 2018',
 10),

('social',
 '70% of people never ask for a raise',
 'Ask for what you''re worth — once a year',
 '70% of employees say they have never negotiated salary',
 '70% of those who do ask for a raise receive one',
 'Salary.com Compensation Survey, 2022',
 9),

('social',
 'Most people react defensively to criticism',
 'Thank critics — treat feedback as data',
 'Default human response to criticism activates threat response in the brain',
 'Thanking critics for feedback is the #1 trait of high-performers in McKinsey talent data',
 'McKinsey & Company Leadership Research',
 7),

('social',
 '84% never read non-fiction after college',
 'Read 10 pages of non-fiction every day',
 'Only 16% of adults read a non-fiction book in a given year',
 'Average CEO reads 60 books/year; reading 10 pages/day = 12 books/year',
 'Inc. Magazine / Pew Research Center, 2021',
 8);
